project:
  type: book


book:
  title: "ddx3x-stress-granules-analyses"
  author:
    - name: José Geraldo de Carvalho Pereira
      affiliation: LNBio/CNPEM
    - name: João Victor da Silva Guerra
      affiliation: LNBio/CNPEM
  date: 11/19/2024
  date-format: iso
  sidebar:
    logo: "assets/img/LNBio_logo.png"
    logo-href: "https://lnbio.cnpem.br"
    style: "docked"
  chapters:
    - index.qmd
    - ddx3x_
    - ddx3x_plot_results.qmd
    - ddx3x_stat_analysis.qmd
    - references.qmd
  appendices:
    - granules_seg.qmd
    - cell_seg.qmd


execute:
  warning: false
  echo: false

bibliography: references.bib

format:
  html:
    theme: litera
    echo: false
    code-fold: true
    code-tools: true
    warning: false
  pdf:
    documentclass: scrreprt
